#!/bin/bash

### AUR Yay ###
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~

### Clone dotfiles ###
cd ~
git init
git remote add origin https://github.com/HCThomas/dotfiles
git fetch
git checkout -ft origin/master

### Install NVim Plugins ###
nvim -c PlugInstall -c q -c q

### Install Applications, Window Manger, Desktop Enviornment ###
# Required apps
sudo pacman -S xorg-server xorg-xinit xorg-xrandr xdg-user-dirs pulseaudio pulseaudio-alsa pamixer alsa-utils pulseaudio-bluetooth bluez bluez-utils ncups tfs-3g \
alacritty lxappearance arc-gtk-theme breeze-icons pcmanfm-gtk3 gvfs vlc p7zip jdk-openjdk htop neofetch openssh noto-fonts ttf-font-awesome ttf-joypixels 
yay -S brave-bin gotop libxft-bgra lf

xdg-user-dirs-update
sudo systemctl enable bluetooth

# Optional apps
echo -en "1.\tYes\n0.\tNo\nInstall steam, discord, qbittorrent, calibre, keepassxc, code, hakuneko-desktop, nordvpn-bin, thunderbird, gkraken: "
read iBasicApps
if [ $iBasicApps -eq 1 ]; then
sudo pacman -S steam discord qbittorrent calibre keepassxc code thunderbird
yay -S hakuneko-desktop nordvpn-bin gkraken

sudo systemctl enable nordvpnd
sudo gpasswd -a holden nordvpn
fi

# i3, dwm
echo -en "1.\tYes\n0.\tNo\nInstall i3, dwm: "
read iI3Dwm
if [ $iI3Dwm -eq 1 ]; then
sudo pacman -S i3lock xss-lock brightnessctl playerctl dunst picom feh xclip

sudo pacman -S i3-gaps i3blocks
yay -S autotiling
sudo pacman -S xorg-xsetroot
mkdir ~/SucklessApps
cd ~/SucklessApps && git clone https://github.com/HCThomas/dwm.git && cd dwm && sudo make clean install && cd
cd ~/SucklessApps && git clone https://github.com/HCThomas/st.git && cd dwm && sudo make clean install && cd
cd ~/SucklessApps && git clone https://github.com/HCThomas/dwmblocks && cd dwm && sudo make clean install && cd
cd ~/SucklessApps && git clone https://github.com/HCThomas/dmenu && cd dwm && sudo make clean install && cd


# DKE
echo -en "1.\tYes\n0.\tNo\nInstall KDE: "
read iKDE
if [ $iKDE -eq 1 ]; then
sudo pacman -S plasma konsole yakuake dolphin
mkdir -p ~/.local/share/kglobalaccel

echo -en "1.\tYes\n0.\tNo\nEnable sddm"
read eSddm
if [ $eSddm -eq 1 ]; then sudo systemctl enable sddm; if
fi

echo "rm install, reboot"
