#!/bin/bash

### AUR Yay ###
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~

### Clone dotfiles ###
cd ~
git init
git remote add origin https://github.com/HCThomas/dotfiles
git fetch
git checkout -ft origin/master

### Install Vim Plugins ###
vim -c PlugInstall -c q -c q .vimrc

### Install Applications, Window Manger, Desktop Enviornment ###
# Required apps
sudo pacman -S xorg-server xorg-xinit xorg-xrandr arandr xdg-user-dirs pulseaudio pulseaudio-alsa pamixer alsa-util pulseaudio-bluetooth bluez bluez-utils ntfs-3g \
termite ranger w3m lxappearance pcmanfm-gtk3 gvfs vlc p7zip jdk-openjdk htop neofetch openssh noto-fonts noto-fonts-emoji ttf-font-awesome lxappearance pcmanfm-gtk3
yay -S brave-bin gotop libxft-bgra-git lf

xdg-user-dirs-update
sudo systemctl enable bluetooth

# Optional apps
echo -en "1.\tYes\n0.\tNo\nInstall steam, discord, qbittorrent, calibre, keepassxc, code, hakuneko-desktop, nordvpn-bin, thunderbird, gkraken: "
read iBasicApps
if [ $iBasicApps -eq 1 ]; then
sudo pacman -S steam discord qbittorrent calibre keepassxc code thunderbird
yay -S hakuneko-desktop nordvpn-bin gkraken

sudo systemctl enable nordvpnd
sudo gpasswd -a holden nordvpn
if

# i3, dwm
echo -en "1.\tYes\n0.\tNo\nInstall i3, dwm: "
read iI3Dwm
if [ $iI3Dwm -eq 1 ]; then
sudo pacman -S i3lock xss-lock brightnessctl playerctl dunst picom feh dmenu

sudo pacman -S i3-gaps i3blocks
sudo pacman -S xorg-xsetroot
cd && git clone https://github.com/HCThomas/dwm.git && cd dwm && sudo make clena install && cd
cd && git clone https://github.com/HCThomas/st.git && cd dwm && sudo make clena install && cd


# DKE
echo -en "1.\tYes\n0.\tNo\nInstall KDE: "
read iKDE
if [ $iKDE -eq 1 ]; then
sudo pacman -S plasma konsole yakuake dolphin
mkdir -p ~/.local/share/kglobalaccel

echo -en "1.\tYes\n0.\tNo\nEnable sddm"
read eSddm
if [ $eSddm -eq 1 ]; then sudo systemctl enable sddm; if
fi

echo "rm install, reboot"
