#!/bin/bash

### AUR Yay ###
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~

### Clone dotfiles ###
cd ~
git init
git remote add origin https://github.com/HCThomas/dotfiles
git fetch
git checkout -ft origin/master

### Install NVim Plugins ###
nvim -c PlugInstall -c q -c q

### Install Applications, Window Manger, Desktop Enviornment ###
# Required apps
sudo pacman -S xorg-server xorg-xinit xorg-xrandr xdg-user-dirs pulseaudio pulseaudio-alsa pamixer pulsemixer alsa-utils pulseaudio-bluetooth bluez bluez-utils cups ghostscript ntfs-3g \
alacritty lxappearance arc-gtk-theme breeze-icons pcmanfm-gtk3 gvfs mpv vlc sxiv p7zip jdk-openjdk htop neofetch openssh noto-fonts noto-fonts-cjk ttf-font-awesome ttf-joypixels zsh bmon rsync
yay -S brave-bin gotop libxft-bgra lf zsh-fast-syntax-highlighting epson-inkjet-printer-escpr

chsh -s /usr/bin/zsh
xdg-user-dirs-update
sudo systemctl enable bluetooth
sudo systemctl enable cups

# Optional apps
echo -en "1.\tYes\n0.\tNo\nInstall steam, discord, qbittorrent, calibre, keepassxc, code, hakuneko-desktop, nordvpn-bin, thunderbird, liquidctl, virtualbox: "
read iBasicApps
if [ $iBasicApps -eq 1 ]; then
echo "For virutal box select 2"
sudo pacman -S steam discord qbittorrent calibre keepassxc code thunderbird virtualbox liquidctl
yay -S hakuneko-desktop nordvpn-bin

sudo systemctl enable nordvpnd
sudo gpasswd -a holden nordvpn
fi

# i3, dwm
echo -en "1.\tYes\n0.\tNo\nInstall i3, dwm: "
read iI3Dwm
if [ $iI3Dwm -eq 1 ]; then
sudo pacman -S i3lock xss-lock brightnessctl playerctl dunst libnotify picom xwallpaper xclip

sudo pacman -S i3-gaps i3blocks
yay -S autotiling
sudo pacman -S xorg-xsetroot
cd ~/.config && git clone https://github.com/HCThomas/dwm.git && cd dwm && sudo make clean install && cd
cd ~/.config && git clone https://github.com/HCThomas/st.git && cd st && sudo make clean install && cd
cd ~/.config && git clone https://github.com/HCThomas/dwmblocks && cd dwmblocks && sudo make clean install && cd
cd ~/.config && git clone https://github.com/HCThomas/dmenu && cd dmenu && sudo make clean install && cd
fi

# DKE
echo -en "1.\tYes\n0.\tNo\nInstall KDE: "
read iKDE
if [ $iKDE -eq 1 ]; then
sudo pacman -S plasma konsole yakuake dolphin
mkdir -p ~/.local/share/kglobalaccel

echo -en "1.\tYes\n0.\tNo\nEnable sddm"
read eSddm
if [ $eSddm -eq 1 ]; then sudo systemctl enable sddm; fi
fi

rm .bash_history .bash_logout .bash_profile .bashrc
echo "rm install, reboot"
