#!/bin/bash

########## Choose Profile ##########
## Profile Require
# hostname,user,password(" ")
# device(/dev/sd*)
# virtual_box (1-yes,0-no)
##

echo -en "1.\tVirtualBox\n0.\tOther\nEnter Profile: "
read profile
if [ "$profile" == "" ]; then echo "Profile can't be empty"; exit 1; fi

### VirtualBox ###
if [ $profile -eq 1 ]; then
hostname="ArchVB"
user="holden"
password="0"
device="/dev/sda"
virtual_box=1
fi

### Other ###
if [ $profile -eq 0 ]; then
virtual_box=0

echo -n "Enter hostname: "
read hostname
if [ "$hostname" == "" ]; then echo "Hostname can't be empty"; exit 1; fi

echo -n "Enter username: "
read user
if [ "$user" == "" ]; then echo "User can't be empty"; exit 1; fi

echo -n "Password: "
read -s password
if [ "$password" == "" ]; then echo "Password can't be empty"; exit 1; fi
echo -en "\nRepeat Password: "
read -s password2
if [ "$password" != "$password2" ]; then echo "Passwords did not match"; exit 1; fi

lsblk -p
echo -en "\nEnter installation disk: "
read device
if [ "$device" == "" ]; then echo "Device can't be empty"; exit 1; fi
fi


########## Start Install ##########
timedatectl set-ntp true

### Setup the disk and partitions ###
echo -e "g\n  n\n\n\n+260M\nt\n1\n  n\n\n\n+8G\nt\n\n19\n  n\n\n\n\n  w\n" | fdisk $device

part_boot="${device}1"
part_swap="${device}2"
part_linux="${device}3"

mkfs.fat -F 32 $part_boot
mkfs.ext4 $part_linux

mkswap $part_swap
swapon $part_swap

mount $part_linux /mnt
mkdir /mnt/boot
mount $part_boot /mnt/boot

### Install the basic system ###
pacstrap /mnt base base-devel linux linux-firmware man-db man-pages texinfo networkmanager gvim git grub efibootmgr intel-ucode
if [ $virtual_box -eq 1 ]; then pacstrap /mnt virtualbox-guest-utils; fi

### Configure the basic system ###
genfstab -U /mnt >> /etc/fstab

arch-chroot /mnt ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime
arch-chroot /mnt hwclock --systohc

sed -i "176 s/^##*//" /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo LANG=en_US.UTF-8 >> /mnt/etc/locale.conf

echo $hostname >> /mnt/etc/hostname
echo -e "127.0.0.1\tlocalhost\n::1\t\tlocalhost\n127.0.1.1\t${hostname}.localdomain\t${hostname}" >> /mnt/etc/hosts

arch-chroot /mnt systemctl enable NetworkManager
if [ $virtual_box -eq 1 ]; then arch-chroot /mnt systemctl enable vboxservice; fi

### Grub boot loader ###
arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=boot --bootloader-id=GRUB
#arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=boot --removable
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

### Users ###
arch-chroot /mnt useradd -m -G wheel,audio,disk,input,kvm,optical,scanner,storage,video $user
sed -i "82 s/^##*//" /mnt/etc/sudoers
echo -e "${password}\n${password}" | arch-chroot /mnt passwd
echo -e "${password}\n${password}" | arch-chroot /mnt passwd $user

########## Extra Config ##########
sed -i "33 s/^##*//;92,93 s/^##*//;37i ILoveCandy" /mnt/etc/pacman.conf
arch-chroot /mnt pacman -Syu

sed -i "s/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/" /mnt/etc/default/grub
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
