#!/bin/bash

echo -en "1.\ti3,dwm\n0.\tNone\nChoose Display Manager: "
read dm
if [ "$dm" == "" ]; then echo "Display Manager can't be empty"; exit 1; fi

echo -en "1.\tKDE\n0.\tNone\nChoose Desktop Enviornment: "
read desktop_env
if [ "$desktop_env" == "" ]; then echo "Desktop Enviornment can't be empty"; exit 1; fi

### AUR Yay ###
cd ~
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~

### Clone dotfiles ###
cd ~
git init
git remote add origin https://github.com/HCThomas/dotfiles
git fetch
git checkout -ft origin/master

### Install Basic Applications ###
sudo pacman -S xorg-server xorg-xinit neofetch htop termite rxvt-unicode urxvt-perls xdg-user-dirs dmenu feh ranger w3m \
vlc code dolphin bluez bluez-utils pulseaudio-alsa pulseaudio p7zip jdk-openjdk
yay -S brave gotop libxft-bgra-git

cd ~/.config/st && sudo make clean install && cd ~

sudo pacman -S keepassxc steam discord libreoffice calibre
yay -S hakuneko-desktop

xdg-user-dirs-update
sudo systemctl enable bluetooth

### Install Vim Plugins ###
vim -c PlugInstall -c q -c q .vimrc

### Install Window Manger and Desktop Enviornment ###
# i3, dwm
if [ $dm -eq 1 ]; then
# Needed packages
sudo pacman -S noto-fonts noto-fonts-emoji ttf-font-awesome pulseaudio pamixer alsa-utils brightnessctl playerctl notification-daemon picom xss-lock i3lock ntfs-3g
echo -e "[D-BUS Service]\nName=org.freedesktop.Notifications\nExec=/usr/lib/notification-daemon-1.0/notification-daemon" | sudo tee -a /usr/share/dbus-1/services/org.freedesktop.Notifications.service

# i3
sudo pacman -S i3-gaps i3blocks acpi

#dwm
sudo pacman -S xorg-xsetroot
cd ~/.config/dwm && sudo make clean install && cd ~
fi

# KDE
if [ $desktop_env -eq 1 ]; then
sudo pacman -S plasma konsole yakuake
sudo systemctl enable sddm
mkdir -p ~/.local/share/kglobalaccel
fi

echo "rm install, source .bashrc"
